FROM alpine:latest

LABEL maintainer="Pedro Sousa <ppls2106@gmail.com>"

RUN apk update

RUN apk add python3 gcc musl-dev python3-dev libffi-dev openssl-dev

RUN pip3 install --upgrade pip

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .
