FROM python:alpine

LABEL maintainer="Pedro Sousa <ppls2106@gmail.com>"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN rm -rf /var/cache/apk/* && \
    apk update && \
    apk add make && \
    apk add build-base && \
    apk add gcc && \
    apk add libffi-dev && \
    apk add musl-dev && \
    apk add openssl-dev && \
    apk del build-base && \
    rm -rf /var/cache/apk/*

RUN pip install --upgrade pip

ENV HOME=/home/api

RUN adduser -D api

WORKDIR $HOME

COPY --chown=api:api . $HOME

RUN chmod +x ./startup.sh

RUN pip3 install --no-cache-dir -r requirements.txt

USER api

EXPOSE 5000

CMD ["./startup.sh"]
