# docker-compose.yml
version: '3'
services:
  flask:
    container_name: fail2ban_iec
    image: fail2ban_iec
    build:
      context: .
      dockerfile: dockerfile_alpine_fail2ban_iec
    command: gunicorn --bind 0.0.0.0:5000 fail2ban:app
    volumes:
    - "./:/app"
    ports:
    - 5000:5000